### ISSUE TITLE
addAttribute exeption

### ISSUE THREAD

**Issue by obukhow** [dankocherga/MTool#28]
"Install" or "upgrade" function should add &lt;class&gt; to &lt;setup&gt; in config.xml.
Like 
&lt;setup&gt;
     &lt;module&gt;Namespace_Module&lt;/module&gt;
     &lt;connection&gt;core_setup&lt;/connection&gt;
     &lt;class&gt;Mage_Sales_Model_Mysql4_Setup&lt;/class&gt;
&lt;/setup&gt;

**Comment by dankocherga** [comment]
I think it's not very good idea since we don't know which class should be used in all cases, so without <class> Magento will use default setup class and users may change it manually to the specific one if needed.
