### ISSUE TITLE
Undo action

### ISSUE THREAD

**Issue by obukhow** [dankocherga/MTool#29]
Reverse action of create functions removing files and config.xml strokes.

**Comment by dankocherga** [comment]
why do you need undo? Use version control software if you need to revert something.

**Comment by obukhow** [comment]
version control is not a magic pill. what if after 10 various creations i want to delete first? How should i restore my config.xml?

**Comment by dankocherga** [comment]
Can you undo "rm -rf /" ?
Don't think about command line tool as a text editor. 

Do a commit on every change as workaround :)

**Comment by obukhow** [comment]
i don't want it to be a real undo. it should be a revert action of create. So if create command adds a file, undo should remove file, if create adds some strings to config.xml, undo should find the same strings and remove them.
