### ISSUE TITLE
Exception thrown during module creation

### ISSUE THREAD

**Issue by marcell** [dankocherga/MTool#32]
An exception is thrown during module creation when the module name contains no slashes. Example:

$ zf create mage-module hello

PHP Notice:  Undefined offset: 1 in /usr/share/php/MageTool/lib/MTool/Mtool/Providers/Module.php on line 46
PHP Stack trace:
PHP   1. {main}() /usr/share/php/zf.php:0
PHP   2. ZF::main() /usr/share/php/zf.php:623
PHP   3. ZF->run() /usr/share/php/zf.php:74
PHP   4. ZF->_runTool() /usr/share/php/zf.php:117
PHP   5. Zend_Tool_Framework_Client_Abstract->dispatch() /usr/share/php/zf.php:600
PHP   6. Zend_Tool_Framework_Client_Abstract->_handleDispatch() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:241
PHP   7. Zend_Tool_Framework_Client_Abstract->_handleDispatchExecution() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:318
PHP   8. call_user_func_array() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:324
PHP   9. Mtool_Providers_Module->create() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:0

Notice: Undefined offset: 1 in /usr/share/php/MageTool/lib/MTool/Mtool/Providers/Module.php on line 46

Call Stack:
    0.0032     809688   1. {main}() /usr/share/php/zf.php:0
    0.0037     809688   2. ZF::main() /usr/share/php/zf.php:623
    0.0110    1313000   3. ZF->run() /usr/share/php/zf.php:74
    0.0111    1313000   4. ZF->_runTool() /usr/share/php/zf.php:117
    0.0131    1452200   5. Zend_Tool_Framework_Client_Abstract->dispatch() /usr/share/php/zf.php:600
    0.3566   11365248   6. Zend_Tool_Framework_Client_Abstract->_handleDispatch() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:241
    0.3568   11365952   7. Zend_Tool_Framework_Client_Abstract->_handleDispatchExecution() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:318
    0.3568   11366584   8. call_user_func_array() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:324
    0.3568   11367072   9. Mtool_Providers_Module->create() /usr/share/php/Zend/Tool/Framework/Client/Abstract.php:0

**Comment by vsushkov** [comment]
@marcell this exception is occurred because of incorrect usage. Use even all-parameters-in-one string or use no parameters at all, than you will be asked for company name etc. please see [the manual](https://github.com/dankocherga/MTool/wiki/Manual)

In your case, you should do something like this:

`zf create mage-module company/hello`
